import Header from '@/components/header'
import '../styles/globals.css'
import '../styles/categories.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PayPalScriptProvider } from '@paypal/react-paypal-js'
import { UserProvider } from '@/providers/UserProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  Component, pageProps
}: any) {

  return (
    <>
      <UserProvider>
        <PayPalScriptProvider options={{ clientId: (process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID as string) }}>
          <>
            <Header />
            <Component {...pageProps} />
          </>
        </PayPalScriptProvider>
      </UserProvider>
    </>
  )
}
