import Header from '@/components/header'
import '../styles/globals.css'
import '../styles/categories.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  Component, pageProps
}: any) {
  return (
    <>
      <Header />
      <Component {...pageProps} />
    </>
  )
}
